### ISSUE TITLE
Change needed to get this compose file working in Swarm

### ISSUE THREAD

**Issue by smakam** [docker/example-voting-app#10]
hi
I got the voting application working in a single node cluster. When I initially tried to use the same Compose file in a Swarm cluster, I got the following error:
Unable to find a node fulfilling all dependencies: --link=examplevotingapp_db_1:db --link=examplevotingap
p_db_1:db_1 --link=examplevotingapp_db_1:examplevotingapp_db_1 --link=examplevotingapp_redis_1:examplevotingapp_redis_1 -
-link=examplevotingapp_redis_1:redis --link=examplevotingapp_redis_1:redis_1

The reason I had this problem was redis and db container were scheduled on 2 different nodes and docker compose could not schedule worker container that links to both redis and db. After some experimentation, I solved this problem by changing "links" to "depends_on" in the compose file. Looks like "links" will schedule containers in same node. Is that correct?
This is what "links" description says in documentation:
"Containers for the linked service will be reachable at a hostname identical to the alias, or the service name if no alias was specified."

Its not clear when links would be absolutely needed?
Is there a way to get this application working with links in Swarm cluster?

Thanks
Sreenivas

**Comment by anroots** [comment]
Similar problem here: https://github.com/docker/compose/issues/1528

@smakam's workaround of modifying `docker-compose.yml` and adding `depends_on` to "force" linked services to be deployed on the same node worked.

I agree that it is not immediately obvious when to use `link` or `network` as the Compose file contains both.

_Compose 1.6.2, Docker 1.10.2, Swarm 1.0.3_
