### ISSUE TITLE
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

### ISSUE THREAD

**Issue by andyfenelon** [docker/example-voting-app#11]
docker-compose up

gives this
`ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.`

**Comment by aanand** [comment]
You're using an old version of Compose which doesn't support the version 2 file format. Upgrade to 1.6.2 to run this app.

**Comment by andyfenelon** [comment]
thanks
