### ISSUE TITLE
Voting server on nodes does not run

### ISSUE THREAD

**Issue by gandhivikas23** [docker/example-voting-app#33]
Voting server on nodes does not run

result_1  | [nodemon] starting `node --debug server.js`
result_1  | _stream_readable.js:498
result_1  |     dest.end();
result_1  |         ^
result_1  | 
result_1  | TypeError: Cannot read property 'end' of null
result_1  |     at Socket.onend (_stream_readable.js:498:9)
result_1  |     at Socket.g (events.js:273:16)
result_1  |     at emitNone (events.js:85:20)
result_1  |     at Socket.emit (events.js:179:7)
result_1  |     at endReadableNT (_stream_readable.js:913:12)
result_1  |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
result_1  |     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by ManoMarks** [comment]
@gandhivikas23 are you still encountering this issue? Can't reproduce
