### ISSUE TITLE
would you provide scalable web app example?

### ISSUE THREAD

**Issue by secjex** [docker/example-voting-app#4]
I don't know how to integrate with HAproxy

**Comment by leandromoreira** [comment]
@secjex this might help you:

- https://bitcontainer.wordpress.com/2015/09/18/scaling-microservices-with-docker-compose-interlock-and-haproxynginx/
- https://blog.docker.com/2015/02/orchestrating-docker-with-machine-swarm-and-compose/
- http://sirile.github.io/2015/05/18/using-haproxy-and-consul-for-dynamic-service-discovery-on-docker.html

**Comment by secjex** [comment]
@leandromoreira thank you for your help
