### ISSUE TITLE
voting does not reflect changes on result app. 

### ISSUE THREAD

**Issue by scripterkaran** [docker/example-voting-app#55]
cloned the repo, ran docker-compose up. 

on voting, the logs gives 

```
vote_1    | 10.0.19.2 - - [22/Dec/2016 20:04:10] "POST / HTTP/1.1" 200 -
worker_1  | Processing vote for 'a' by 'cceb022e236a011b'
db        | ERROR:  duplicate key value violates unique constraint "votes_id_key"
db        | DETAIL:  Key (id)=(cceb022e236a011b) already exists.
db        | STATEMENT:  INSERT INTO votes (id, vote) VALUES ($1, $2)
```

also it does not reflect any change on the result app , even when voting for the first time.

**Comment by MarcusSjolin** [comment]
I get the same here, just tried this out. Running just 'docker-compose up' as well. 

```
worker_1  | Processing vote for 'b' by '8a4e378379aa1e87'
db        | ERROR:  duplicate key value violates unique constraint "votes_id_key"
db        | DETAIL:  Key (id)=(8a4e378379aa1e87) already exists.
```

**Comment by mkhaas** [comment]
Received same error running docker-compose up ...

vote_1    | 192.168.56.1 - - [23/Dec/2016 22:12:07] "GET / HTTP/1.1" 200 -
vote_1    | 192.168.56.1 - - [23/Dec/2016 22:12:15] "POST / HTTP/1.1" 200 -
worker_1  | Processing vote for 'a' by 'c96bc9b2b781af9c'
db        | ERROR:  duplicate key value violates unique constraint "votes_id_key"
db        | DETAIL:  Key (id)=(c96bc9b2b781af9c) already exists.
db        | STATEMENT:  INSERT INTO votes (id, vote) VALUES ($1, $2)
vote_1    | 192.168.56.1 - - [23/Dec/2016 22:12:54] "POST / HTTP/1.1" 200 -
worker_1  | Processing vote for 'b' by 'c96bc9b2b781af9c'
db        | ERROR:  duplicate key value violates unique constraint "votes_id_key"
db        | DETAIL:  Key (id)=(c96bc9b2b781af9c) already exists.
db        | STATEMENT:  INSERT INTO votes (id, vote) VALUES ($1, $2)

**Comment by ManoMarks** [comment]
I reverted #54 which appeared to be causing the issue. This should work now, if you pull again. We will keep this issue open until we can bring back connection pooling without causing a duplicate key.

**Comment by thanley11** [comment]
I upgraded to postgres 9.6 and am now using the upsert functionality. 
```
INSERT INTO votes (id, vote) VALUES (@id, @vote) ON CONFLICT (id) DO UPDATE SET vote = @vote.  
```
I think that is misleading, as the exception should be caught in the code and the update should happen. One issue I found is that the results app is not really connecting to postgres because of this in result/server.js:  
```
var config = {
   host: 'db', // Need to change to name of alias in docker-compose ('db'), instead of host: 'localhost',
   user: 'postgres',
   password: '',
   database: 'postgres',
   ...
   });
 });
```
I changed this and also modified the getVotes function and it is all working:
```
 function getVotes(client) {
  client.query('SELECT vote, COUNT(id) AS count FROM votes GROUP BY vote ORDER BY vote ASC', [], function(err, result) {
     if (err) {
       console.error("Error performing query: " + err);
     } else {
        var votes = result.rowCount;
        if (result.rowCount < 2){
            votes = [result.rows[0], {"count" : 0} ];
        }
        else {
            votes = [result.rows[0], result.rows[1]];
        }
       io.sockets.emit("scores", JSON.stringify(votes));
     }
     setTimeout(function() {getVotes(client) }, 1000);
});
}
```

And in result/views/app/js
```
  var updateScores = function(){
    socket.on('scores', function (json) {
       data = JSON.parse(json);
       var a = parseInt(data[0].count || 0);
       var b = parseInt(data[1].count || 0);

       var percentages = getPercentages(a, b);

       bg1.style.width = percentages.a + "%";
       bg2.style.width = percentages.b + "%";

       $scope.$apply(function () {
         $scope.aPercent = percentages.a;
         $scope.bPercent = percentages.b;
         $scope.total = a + b;
       });
    });
  };

```

**Comment by spara** [comment]
The duplicate key error occurs when you try to vote more than once from the same client. Each vote is inserted into the database using a cookie generated by the vote application. When you try to vote from the same client it will use the same id from the cookie which violates the duplicate key constraint in the database. Will not fix.

**Comment by rrmhearts** [comment]
For production, that makes sense as a constraint. When testing on a two node swarm, very confusing! I'm glad I found this page!

**Comment by kiritocr7** [comment]
https://github.com/dockersamples/example-voting-app/issues/55#issuecomment-269395120
This worked for me. Thanks @thanley11. And there was an issue with worker app dotnet code. So I used the java dockerfile and created the image and used it for running on Kubernetes container and it worked.
