### ISSUE TITLE
Error response from daemon: client is newer than server (client API version: 1.2 2, server API version: 1.21)

### ISSUE THREAD

**Issue by rsdrichard** [docker/example-voting-app#6]

**Comment by kongslund** [comment]
You need Docker 1.10.0.

**Comment by bfirsh** [comment]
You need to upgrade your Docker daemon. If you are using Docker Toolbox, [download the latest version](https://www.docker.com/products/docker-toolbox) and run `docker-machine upgrade`.

**Comment by mohan08p** [comment]
What you can do, download [Docker Version Manager(DVM)](https://github.com/getcarina/dvm) and 
**$ dvm ls**
          1.11.0
          1.11.1
          1.11.2
 ->      system(1.12.0)

It will list out the different version and you can choose the appropriate with,
**$ dvm use 1.11.2**
Now using Docker 1.11.2

Now, your docker version is compatible.
