### ISSUE TITLE
"volumes must be a mapping" while trying to deploy this file

### ISSUE THREAD

**Issue by Tirocigno** [docker/example-voting-app#75]
Followed the procedure at (https://docs.docker.com/engine/getstarted-voting-app/node-setup/#interacting-with-the-machines), copy and pasted the file in the right directory of the manager.
When i launch `docker stack deploy --compose-file docker-stack.yml vote` i get  `volumes must be a mapping"`
I'm working on Ubuntu 16.10, i tried also with Windows and it works fine.

**Comment by ManoMarks** [comment]
@Tirocigno can you give the results of `docker version`?

**Comment by samanta60** [comment]
Hi 
I have the same problem. I am using Centos guest in Vmware on Windows host.

Output of docker version on manager machine:
docker@manager:~$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: false


on localhost:
docker@manager:~$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by samanta60** [comment]
Problem SOLVED!

The issue simply was: I had downloaded the docker-stack.yml file in windows and then copied it into linux. 
I directly created the file in centos now, and it deployed the voting app successfully.

**Comment by ManoMarks** [comment]
Could be a text encoding issue. @Tirocigno can you check that?

**Comment by londoncalling** [comment]
@samanta60 Can you tell me what was happening when you tried the direct download? Was the content of the file changed in some way? 

I probably need to add something to the docs about this, with a little warning and example?

**Comment by samanta60** [comment]
@londoncalling: Sure! Each line in the file was ending with ^M, which I think always happens if you first save the file in windows and then copy and use it in linux. 
I could see the ^M at the end of each line, when I opened the docker-stack.yml file using vi command in linux.

**Comment by londoncalling** [comment]
@samanta60 thanks! I'm going to add a note to the docs as a tip/caveat. Much appreciated.

**Comment by ManoMarks** [comment]
Yup, encoding problem! I'm closing this issue. @Tirocigno if this doesn't solve your problem, please re-open the issue.

**Comment by Tirocigno** [comment]
Problem solved! Thanks everybody.
