### ISSUE TITLE
Update .NET Worker to v1.0.0 SDK

### ISSUE THREAD

**Issue by richlander** [docker/example-voting-app#77]
The .NET part of the sample (https://github.com/docker/example-voting-app/tree/master/worker) is now using an old .NET Core SDK. It needs to be updated, both in the Dockerfile and move to csproj (as opposed to project.json). I assume that actual code doesn't need to be changed. There is an opportunity to move it to C# 7 if there are some good cases for that (I didn't look).

We should treat DockerCon as the deadline for this, in case anyone gets interested in the combination of .NET and Docker together. Imagine that!

Hey, @kendrahavens @michaelsimons ... can one of you do this?

**Comment by ManoMarks** [comment]
Looks like 1.1.1 is latest. I'm on it
