### ISSUE TITLE
Question: Debugging .NET part

### ISSUE THREAD

**Issue by sadedil** [docker/example-voting-app#81]
Hi,

I'm not sure to asking questions here is appropriate but i need some help.
`docker-compose up` command works in my machine without problem but i want to try debug **only** .NET worker project with Visual Studio or VS Code.

I don't know where to start? How to prepare project structure? How to configure dockerfile or docker-compose.yml?

**Comment by alexsandro-xpt** [comment]
Look for principle, I will open only work project at VS for debug and expose the REDIS end postgresql port for connect.

But may have another better and practical way.

**Comment by ManoMarks** [comment]
@sadedil I'm going to close this issue since this isn't the right place to ask that question. Please head over to the Docker Forums: https://forums.docker.com/ or the Docker Community https://community.docker.com to start a discussion.
